### ISSUE TITLE
Obsolete records break the Archives Admin

### ISSUE THREAD

**Issue by elliot-sawyer** [silverstripe/silverstripe-versioned-admin#350] opened 2024-06-18 04:58 UTC
### Module version(s) affected

2.2.0

### Description

If any obsolete class records are present in the Archives Admin, it fails with the following error:
`Uncaught BadMethodCallException: Object->__call(): the method 'getLastEdited' does not exist on 'SilverStripe\ORM\DataObject'`

This is because non-existent classes default to DataObject, which does not have an actual `LastEdited` database column. Commenting out [this line](https://github.com/silverstripe/silverstripe-versioned-admin/blob/2/src/ArchiveAdmin.php#L165) sort of* resolves the issue: it allows the Gridfield to load, but any pages with a broken/obsolete record will throw a 500 error

### How to reproduce

Not 100% sure how to reproduce, but:

- Create some custom pagetype and publish it
- archive it
- delete the pagetype class and do a dev/build so the record is still in the database but with an invalid class
- open archives admin and :crossed_fingers: observe a failure

### Possible Solution

Adding this method to DataObject.php via an Extension makes the issue go away:

```php
    public function getLastEdited()
    {
        return $this->owner->dbObject('LastEdited') ?? '';
    }
```

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by GuySartorelli** [comment] 2024-06-18 23:37
I can't reproduce this - following those instructions, the page shows up fine in archive admin, and its page type is displayed as "Page" - i.e. it falls back to `Page`, not to `DataObject`.

**Comment by elliot-sawyer** [comment] 2024-06-18 23:41
The records in question used to be Mailchimp newsletter pages, but the module was removed at some point.  Perhaps it was unpublished after the module was removed.

**Comment by elliot-sawyer** [comment] 2024-06-18 23:42
Not hugely urgent since the posted workaround works for us, I thought I'd post it here to share with anyone else who hits the issue :+1:

**Comment by GuySartorelli** [comment] 2024-06-19 00:22
Tried archiving _after_ deleting the custom page class and dev/build but got the same result.

If someone can find a way to reproduce this that'd be great - if not, it will likely be closed at some stage in the future.

**Comment by GuySartorelli** [comment] 2024-08-04 23:14
Closing as there are no new reproduction steps. If someone can reproduce, feel free to `@` me with more details and I'll look at it again.

**Closed as not planned by GuySartorelli** 2024-08-04 23:14 UTC
