### ISSUE TITLE
Better documentation on integrating with 3rd party DataObjects

### ISSUE THREAD

**Issue by ishannz** [silverstripe/silverstripe-versioned-admin#104] opened 2019-03-14 00:27 UTC
At the moment the information is quite scarce, and even after creating all the requisite GraphQL and code to power the history viewer, compiling the resulting project code is fraught with errors regarding `'lib/Injector'` which cannot be found.

Even after adjusting the webpack config to allow for this (and include the externals reference) the error persists. Clear documentation from 'real world' (project rather than module) use cases would be extremely helpful in this case.

**Comment by robbieaverill** [comment] 2019-03-14 00:37
Are you referring to https://docs.silverstripe.org/en/4/developer_guides/model/versioning/#using-the-history-viewer? From memory this was written from a project level context. Unfortunately, using the history viewer is inherently difficult due to the way that GraphQL scaffolding works requiring specific queries needing to be written for each model, rather than one generic query with a toggle for the class name. I agree that this documentation should work out of the box though.

**Comment by ScopeyNZ** [comment] 2019-03-20 22:54
I've come across this `'lib/Injector'` problem as described recently. The problem was only caused by eslint though. @ishannz, were eslint failures preventing the project code from building correctly in your case?

The problem here is that eslint doesn't use the same method as webpack for resolving imports. This means that although the build might work correctly (the outputted javascript works and imports are resolved), eslint can't understand the imports and reports an error.

This can be resolved by ensuring that a development version of `silverstripe/admin` is installed. Simply `yarn install`ing within the admin directory is not sufficient. Potentially we should fix our eslint configuration to import properly - which includes ignoring imports that are registered as "externals".

**Comment by GuySartorelli** [comment] 2023-03-13 04:05
eslint isn't necessary with `@silverstripe/webpack-config` 1.x, and the documentation had said to use 0.x
I'm updating this as part of https://github.com/silverstripe/developer-docs/issues/164 - the update will include the CMS 4 docs and resolves the specific problem described in this issue.
Closing.

**Closed by GuySartorelli** 2023-03-13 04:05 UTC
Labels: affects/v4, complexity/medium, impact/low, type/docs
