### ISSUE TITLE
History Viewer: page preview 404 after upgrade

### ISSUE THREAD

**Issue by scott-nz** [silverstripe/silverstripe-versioned-admin#100] opened 2019-02-08 01:30 UTC
After upgrading from CWP1.9 to CWP2.1 any versions created before the upgrade return a 404 in the page preview panel.
Content does correctly load in the history panel.
any versions published after the upgrade will load correctly in the page preview. @maxime-rainville

**Comment by robingram** [comment] 2019-02-08 02:04
@scott-nz Was this working for you in 1.9? We also noticed this as part of an ongoing upgrade but are seeing 503 errors when we try the same thing on the current CWP 1.9 instances.

**Comment by robingram** [comment] 2019-02-08 02:07
To clarify, normal preview in split screen works fine for us but if we try split screen in the History tab the frame containing the preview gives a 404 in CWP 2.2 or a 503 in CWP 1.9.

**Comment by scott-nz** [comment] 2019-02-08 02:14
This is working in CWP 1.9 for me. 
Normal preview split screen is working correctly.

**Comment by maxime-rainville** [comment] 2019-02-08 08:43
I've confirmed the behavior on a Vanilla SS44 site. https://youtu.be/8NIV2ticA3M

# Steps to reproduce
* Access a site that got upgrade from SilverStripe 3 to SilverStripe 4.
* Edit a page.
* Look at previous versions that got created in SS3.

The readonly form loads fine, but the preview windows returns a 404. You can restore previous versions fine.

# Cause of the problem

The iframe URL will look something like this: `/about-us/?stage=Stage&archiveDate=2019-02-08 20:57:07`.

The query for retrieving the page has the following condition that SS3 versions of the page fail `"SiteTree_Versions"."WasDraft" = 1`. `WasDraft` for SS4 versions of the page is set to `true`.

If the stage is set to `Live` for that URL, the page is retrieve successfully because `WasDraft` is swap for `WasPublished`.

My guess right now is we either need to remove the `WasDraft` condition from the query in Versioned or we need to make sure WasDraft is set to true when importing SS3 Versioned records.

**Comment by maxime-rainville** [comment] 2019-02-08 08:56
@chillu Do we want to add this to our Smoother upgrade epic?

I'm calling this `[impact/medium]`, because you can still view the content on the readonly form ... unless there's another use case for the `archiveDate` versioned reading mode, in which case this is probably `[impact/high]`.

**Comment by pjayme** [comment] 2019-02-13 00:50
Hi there, 

Am also in the middle of an upgrade project (SS3 to SS4) and am experiencing identical issues where I receive a `404 error` on the preview link in the CMS.

Maxime's response above captures the issue picture perfect:

> I've confirmed the behavior on a Vanilla SS44 site. https://youtu.be/8NIV2ticA3M
> 
> # Steps to reproduce
> * Access a site that got upgrade from SilverStripe 3 to SilverStripe 4.
> * Edit a page.
> * Look at previous versions that got created in SS3.
> 
> The readonly form loads fine, but the preview windows returns a 404. You can restore previous versions fine.
> 
> # Cause of the problem
> The iframe URL will look something like this: `/about-us/?stage=Stage&archiveDate=2019-02-08 20:57:07`.
> 
> The query for retrieving the page has the following condition that SS3 versions of the page fail `"SiteTree_Versions"."WasDraft" = 1`. `WasDraft` for SS4 versions of the page is set to `true`.
> 
> If the stage is set to `Live` for that URL, the page is retrieve successfully because `WasDraft` is swap for `WasPublished`.
> 
> My guess right now is we either need to
> 
> * remove the `WasDraft` condition from the query in Versioned or
> * make sure `WasDraft` is set to true when importing SS3 Versioned records.
> 
> Probably worth mentioning that if we go with the second solution, folks who have already upgrade are hosed because there's not an elegant way of retroactively fixing that data.

**Comment by maxime-rainville** [comment] 2019-02-13 02:55
@tractorcow Not 100% sure off the purpose of `WasDraft`. How do I get it set to `false` on a regular workflow? Is it meant for versions that got save with `writeToStage(Versioned::Live)`?

Would it be safe to have it default to true when migrating data from SS3?

**Comment by chillu** [comment] 2019-03-01 03:24
@maxime-rainville Not too keen to add `impact/medium` issues to the epic we're trying to close out, but thanks for highlighting it. Given that you can view the older versions in the readonly form, this regression is removing an alternative path to the same information, rather than breaking that use case. In this light, I think you've classified it correctly as `impact/medium`.

This might become `impact/high` if we're currently causing corrupted data during migrations which we can't fix later. Can't we just set `WasDraft=1` where `WasDraft=NULL` in the migrated rows? @unclecheese Can you chime in here please? You've introduced `WasDraft` with https://github.com/silverstripe/silverstripe-versioned/commit/149ab5d8f01269521e5c6bc333aeb8550100b34d

> remove the `WasDraft` condition from the query in Versioned 

How feasible is it to remove that condition? Presumably it was added for a reason?

**Comment by camfindlay** [comment] 2019-06-27 00:29
Ping... any movement on this fix?

**Comment by wilr** [comment] 2019-06-27 01:12
This `WasDraft` column might also be the cause of related history issue (https://github.com/silverstripe/silverstripe-cms/issues/2448)

**Comment by chillu** [comment] 2019-07-30 03:46
There's been a pull request since last week, which is connected to this issue but won't alert subscribers here - so re-posting: https://github.com/silverstripe/silverstripe-versioned/pull/240

**Comment by tractorcow** [comment] 2019-07-30 21:01
Sorry, I was the one who wrote WasDraft, not @unclecheese 📦 

Long story short, when migrating an SS3 site to SS4, WasDraft should be set to true if it was previously null.

**Comment by tractorcow** [comment] 2019-07-30 21:03
@chillu finish `MigrationTask` from a decade ago? :P haha.

**Comment by chillu** [comment] 2019-07-30 21:44
OK, based on my testing Max's PR doesn't cut it (`Boolean(1)`), and we might need to fix this on a migration task level (for new migrations).

In addition, I think we need to create a more specialised migration task to retroactively apply this to versions created under 3.x. This will require everyone running the task to put in a date at which the new site went live, and our task to figure out what `_versions` tables to run this on.

**Comment by chillu** [comment] 2019-07-30 22:20
> OK, based on my testing Max's PR doesn't cut it (Boolean(1)),

Talked to Max, and I was wrong, did the steps in an order that wouldn't happen this way during an actual migration, so his fix does apply for *new* migrations. We agreed that we need a task to fix up *existing* migrated content.

**Comment by tractorcow** [comment] 2019-08-01 01:20
@chillu how about allowing us to specify a separate value to inject for existing rows when adding the new column, but not affecting the default value for future rows? 

E.g. add column with default 1, then immediately modify to default 0 during build.

**Comment by tractorcow** [comment] 2019-08-01 01:25
Alternative, add `onAddDatabaseColumn` / `onUpdateDatabaseColumn` and let user code handle the events.

**Comment by chillu** [comment] 2019-08-01 21:38
> @chillu how about allowing us to specify a separate value to inject for existing rows when adding the new column, but not affecting the default value for future rows?

That would be cleaner, but I'm assuming that we always set a `WasDraft` value when a new version is written, rather than relying on the database default. So it wouldn't change much in actual outcomes of version writes in 4.x right now?

**Comment by tractorcow** [comment] 2019-08-05 04:45
> but I'm assuming that we always set a WasDraft value when a new version is written,

You shouldn't do that, no, since an unpublish is a new "version" (a deleted record on live) that has WasDraft = 0.

You can safely assume that for historic records only, since unpublish never created a version in ss3.

**Comment by tractorcow** [comment] 2019-08-05 04:47
Yes, hence suggested that the DB default is kept at 0 (to be consistent with other bools) and let the code set the default on new rows. :)

**Comment by maxime-rainville** [comment] 2019-11-17 22:05
> How about allowing us to specify a separate value to inject for existing rows when adding the new column, but not affecting the default value for future rows?
> 
> E.g. add column with default 1, then immediately modify to default 0 during build.
> 
> Alternative, add onAddDatabaseColumn / onUpdateDatabaseColumn and let user code handle the events.

That sounds like a cool improvement to consider, but probably beyond the scope of what's needed to fix this particular issue. I think we should consider merging the PR as is to help people who have yet to migrate and maybe provide a side tasks to update the `WasDraft` column base on a specified date.

**Comment by madmatt** [comment] 2019-12-11 23:15
@maxime-rainville I don't see a related PR, is it #137?

**Comment by brynwhyman** [comment] 2019-12-12 22:27
@madmatt try, https://github.com/silverstripe/silverstripe-versioned/pull/240? Looks like it's only for _new_ migrations.

**Comment by maxime-rainville** [comment] 2019-12-15 22:30
#137 tries to fix a different issue that has similar symptoms. I just merged silverstripe/silverstripe-versioned#240 which will fix future migration, but not old ones.

The best way to fix old migration is to write a quick task that updates all version created before the migration date to have WasDraft set to true. @madmatt if you feel like writing such a task maybe hit me up and I can give you some pointers.

**Comment by emteknetnz** [comment] 2022-06-15 02:10
This is an old issue, and I'm going to assume that it's no longer an issue as page preview has been fine during manual testing for some time

**Closed by emteknetnz** 2022-06-15 02:10 UTC
Labels: type/bug, affects/v4, effort/medium, impact/high
